apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
  namespace: myapp
spec:
  template:
    spec:
      containers:
      - name: hello
        image: hello-world
      restartPolicy: Never
  backoffLimit: 2