apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqldb
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-root-password
              key: db_root_password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: db_password
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql2
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc-2
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: myapp
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP